### PR TITLE
solc 0.4.19

### PR DESCRIPTION
**Pull request by denys-popov**
new version of solc

### CODE REVIEW

**Comment by denys-popov** [comment]
Strange I run it on https://travis-ci.org/purblind/truffle-compile/jobs/318270495
and everything fine.

**Comment by cedricwalter** [comment]
hi what the status on this PR?

**Comment by gnidan** [comment]
Planning to get this upgrade out in a patch release next week. Thanks for the contribution here!

@purblind would you mind pulling changes upstream from `develop` on your branch? I think you are missing a [change](https://github.com/trufflesuite/truffle-compile/pull/38) that I suspect is causing the build failure, and would just like to validate that hypothesis.

Thanks!

**Comment by denys-popov** [comment]
@gnidan fixed :)

**Comment by gnidan** [comment]
Travis is still failing on the AST test. I'll have to investigate further.

I prefer the scientific method when my hypotheses are correct -___-

**Comment by gnidan** [comment]
Caught it, problem with `outputSelection`. Merging!

Thanks for the PR!

**Pull request merged**
